major rework of tag-record parsing and choice presentation
Default universal-ctags invocation adds fields to assist impl.
gotofileline learns to comprehend tags-file line format
new: try "${tagnm}.cmake"
fix: don't exclude 1-candidate tagdefs from choice-related massaging
fix: Coverity CID 184286, CID 184290: tagfind.cpp
fix: compound->leaf tag conversion-try
future:
  DBG-log uctag:// URI on gotoTag; uctag: C++ class in namespace
  learn to dynamically dispatch arg "scheme://..." setfile based on scheme
  setfile learns ctag://... URI scheme processing (rudimentary)
  project-specific ctags config tuning
misc:
  add CMake-help-search as an explicit web-search option
  darken ftype:python color-set

diff --git a/test_tagfind b/test_tagfind
--- a/test_tagfind
+++ b/test_tagfind
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 #
-# Copyright 2015-2018 by Kevin L. Goodwin [fwmechanic@gmail.com]; All rights reserved
+# Copyright 2015-2019 by Kevin L. Goodwin [fwmechanic@gmail.com]; All rights reserved
 #
 # This file is part of K.
 #
@@ -52,9 +52,10 @@ for tag in "${test_tags[@]}"; do
 done
 
 chk_tagged_files() {
-   local ref="$(grep -P '\t1;"\tfile\s*$' tags | cut -f2 | sort -u | wc -l)"
-   local tst="$(./"$tgtexe" "<tagged-files>" | wc -l)"
-   ((tst==ref)) || die "FAIL: for T=$1, expected $ans, got $lc"
+   local file_tag_field=$'\t'"kind:file"
+   local ref="$(grep -P "$file_tag_field"'(\t|$)' tags | cut -f2 | sort -u | wc -l)"
+   local tst="$(./"$tgtexe" "$file_tag_field" | wc -l)"
+   ((tst==ref)) || die "FAIL: for T=$1, expected $ref, got $lc"
    }
 
 chk_tagged_files
